version: '3'
services:
   web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
   db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: hueIT
      MYSQL_USER: hueIT
      MYSQL_PASSWORD: hello
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
volumes:
   devDB:
